[project]
name = "MLCICDAnalyzer"
version = "0.1.0"
description = "Synthesize GitHub Actions Workflows via Runtime-based Analysis"
readme = "README.md"
requires-python = ">=3.10"
license = ""
keywords = [
  "github actions",
  "code generation",
  "runtime analysis",
]
authors = [
  { name = "Javid Ditty", email = "jditty@umich.edu" },
  { name = "Rahul Ghanshyam Chavan", email = "rchavan@umich.edu" },
  { name = "Foyzul Hassan", email = "foyzul@umich.edu" },
]
maintainers = [
  { name = "Javid Ditty", email = "jditty@umich.edu" },
  { name = "Rahul Ghanshyam Chavan", email = "rchavan@umich.edu" },
  { name = "Foyzul Hassan", email = "foyzul@umich.edu" },
]
dependencies = [
  "jsonschema>=4.24.0",
  "numpy>=2.2.6",
  "openai>=1.86.0",
  "pyinstaller>=6.14.1",
  "pymoo>=0.6.1.5",
  "qdrant-client>=1.14.3",
  "requirements-parser>=0.13.0",
  "ruamel.yaml>=0.18.14",
  "toml>=0.10.2",
  "tqdm>=4.67.1",
  "tree_sitter>=0.24.0",
  "tree_sitter_bash>=0.23.3",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]

[project.urls]
Documentation = "https://github.com/foyzulhassan/MLCICDAnalyzer#readme"
Issues = "https://github.com/foyzulhassan/MLCICDAnalyzer/issues"
Source = "https://github.com/foyzulhassan/MLCICDAnalyzer"