[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "MLCICDAnalyzer"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.11"
license = ""
keywords = []
authors = [
  { name = "Javid Ditty", email = "jditty@umich.edu",
    name = "Rahul Ghanshyam Chavan", email = "rchavan@umich.edu",
    name = "Foyzul Hassan", email = "foyzul@umich.edu"
  },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/foyzulhassan/MLCICDAnalyzer#readme"
Issues = "https://github.com/foyzulhassan/MLCICDAnalyzer/issues"
Source = "https://github.com/foyzulhassan/MLCICDAnalyzer"

[tool.hatch.version]
path = "src/ci_config_generator/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/ci_config_generator tests}"

[tool.coverage.run]
source_pkgs = ["ci_config_generator", "tests"]
branch = true
parallel = true
omit = [
  "src/ci_config_generator/__about__.py",
]

[tool.coverage.paths]
ci_config_generator = ["src/ci_config_generator", "*/MLCICDAnalyzer/src/ci_config_generator"]
tests = ["tests", "*/MLCICDAnalyzer/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
