# ========================================================================== #
#                                 REQUIRED                                   #
# ========================================================================== #

# name of the workflow to be produced (will be used to create the output directory)
workflow_name = "workflow"

# ordered list of absolute paths to target scripts 
target_paths = []

# absolute path to a directory where outputs will be stored
output_dir = ""

# absolute path to a directory of the repository
repository_dir = ""

# absolute path to a pip requirements file
requirements_path = ""

# ========================================================================== #
#                                 Optional                                   #
# ========================================================================== #

# OpenAI API key for LLM interaction
# - Missing: Model recommendations will be unavailable
api_key = ""

# absolute path to a directory to run targets in
# - Missing: Repository directory will be the working directory
working_dir = ""

# absolute path to a log listing the docker containers on the machine (generated with this tool)
# - Missing: Service-based recommendations will not be provided
docker_path = ""