# ========================================================================== #
#                                 REQUIRED                                   #
# ========================================================================== #

# name of the workflow to be produced (will be used to create the output directory)
workflow_name = ""

# ordered list of absolute paths to target scripts 
target_paths = []

# absolute path to a directory where outputs will be stored
output_dir = ""

# absolute path to a directory of the repository
repository_dir = ""

# absolute path to a pip requirements file
requirements_path = ""

# absolute path to a directory to run targets in
working_dir = ""

# ========================================================================== #
#                                HEURISTIC                                   #
# ========================================================================== #

# weights for Multi-Criteria Decision Making (MCDM) to distribute steps such that:
# - the difference in duration between each step is minimized
# - the total number of steps is maximized
step_mcdm_weights = [0.6, 0.4]

# number of potential step chunks to consider when distributing commands
step_chunk_count = 100000

# job duration thresholds over which syntax can be recommended
recommendation_threshold = { concurrency = 138, fail_fast = 66, timeout_minutes = 319 }

# multipliers to apply to job durations to determine syntax values
recommendation_multiplier = { timeout_minutes = 13 }

# ========================================================================== #
#                                   LLM                                      #
# ========================================================================== #

# OpenAI API key for LLM interaction
# - Missing: Model recommendations will be unavailable
api_key = ""

# OpenAI model name for LLM interaction
# - Missing: Model recommendations will be unavailable
model = "gpt-4o-mini"

# ========================================================================== #
#                                DEPRECATED                                  #
# ========================================================================== #

# absolute path to a log listing the docker containers on the machine (generated with this tool)
# - Missing: Service-based recommendations will not be provided
docker_path = ""