import os
from openai import OpenAI


class ImproveCIWithLLM:
    def __init__(self, api_key):
        # Initialize the OpenAI client with the API key
        self.client = OpenAI(api_key=api_key or os.environ.get("OPENAI_API_KEY"))

    def improve_ci(self, target, requirements, generated_yaml, project_description):
        # Handle target as a directory or a single file
        target_content = ""
        if os.path.isdir(target):
            # Read all .sh files in the directory
            for script in sorted(os.listdir(target)):
                script_path = os.path.join(target, script)
                if script.endswith('.sh'):
                    with open(script_path, 'r') as file:
                        target_content += f"# {script}\n"  # Include script name as a comment
                        target_content += file.read() + "\n"
        else:
            # Single target file
            with open(target, 'r') as file:
                target_content = file.read()

        # Read other input files
        with open(requirements, 'r') as file:
            requirements_content = file.read()

        with open(generated_yaml, 'r') as file:
            generated_yaml_content = file.read()

        with open(project_description, 'r') as file:
            project_description_content = file.read()

        # System instruction for the LLM
        system_instructions = """
        You are an expert in CI/CD workflows and GitHub Actions. Your task is to improve the provided CI configuration 
        script and justify every change made. The following files are given:
        - The combined target bash scripts or single target script.
        - The requirements.txt containing dependencies.
        - The current CI YAML file generated by a tool.
        - A project description file to give context.

        Tasks:
        1. Improve the CI YAML file for:
           - Security
           - Scalability
           - Compatibility with the project requirements
           - Best practices for machine learning workflows
        2. Provide a revised YAML file.
        3. Explain the reasoning behind each improvement made to the YAML configuration.
        """

        # Construct the message payload
        messages = [
            {"role": "system", "content": system_instructions},
            {"role": "user", "content": f"Project Description:\n{project_description_content}"},
            {"role": "user", "content": f"Combined Target Scripts:\n{target_content}"},
            {"role": "user", "content": f"Requirements File (requirements.txt):\n{requirements_content}"},
            {"role": "user", "content": f"Generated CI YAML File:\n{generated_yaml_content}"}
        ]

        # Call the OpenAI API
        chat_completion = self.client.chat.completions.create(
            messages=messages,
            model="gpt-4o"
        )

        # Extract and return the improved YAML
        ciyaml_improved_by_llm = chat_completion.choices[0].message.content
        return ciyaml_improved_by_llm
