import os
import yaml
from copy import deepcopy

# final
class OutputsRecommendation:
    def __init__(self, yaml_file, strace_file, target_scripts_dir):
        self.yaml_file = yaml_file
        self.strace_file = strace_file
        self.target_scripts_dir = target_scripts_dir
        self.workflow = None
        self.recommendations = []

    def validate_yaml(self):
        """
        Validate the YAML file.
        """
        try:
            with open(self.yaml_file, 'r') as file:
                self.workflow = yaml.safe_load(file)
            return True
        except yaml.YAMLError as exc:
            print(f"Error parsing YAML file: {exc}")
            return False
        except FileNotFoundError:
            print(f"YAML file '{self.yaml_file}' not found.")
            return False

    def parse_strace(self):
        """
        Parse the strace log for file creation or modification system calls.
        """
        output_files = set()
        try:
            with open(self.strace_file, 'r') as file:
                for line in file:
                    if "open(" in line or "write(" in line:
                        # Extract file paths or file names
                        parts = line.split('"')
                        if len(parts) > 1:
                            output_files.add(parts[1])
        except FileNotFoundError:
            print(f"Strace file '{self.strace_file}' not found.")
        return output_files

    def parse_target_scripts(self):
        """
        Parse target scripts for file creation or write operations.
        """
        output_files = set()
        for root, dirs, files in os.walk(self.target_scripts_dir):
            for file in files:
                if file.endswith('.sh'):
                    script_path = os.path.join(root, file)
                    with open(script_path, 'r') as script_file:
                        for line in script_file:
                            if ">" in line or ">>" in line:
                                # Extract potential output files
                                parts = line.split()
                                for part in parts:
                                    if part.startswith(">") or part.startswith(">>"):
                                        output_files.add(part.lstrip(">"))
        return output_files

    def generate_recommendation(self):
        """
        Generate recommendations for adding outputs to the workflow YAML.
        """
        if not self.validate_yaml():
            return {"error": "Invalid YAML file"}

        output_files = self.parse_strace().union(self.parse_target_scripts())
        updated_workflow = deepcopy(self.workflow)

        for job_id, job in updated_workflow.get('jobs', {}).items():
            if 'outputs' not in job and output_files:
                job['outputs'] = {
                    file.split("/")[-1]: f"${{{{ steps.{file.split('/')[-1]}.outputs }}}}"
                    for file in output_files
                }
                self.recommendations.append({
                    "job_id": job_id,
                    "recommendation": "Added outputs for files generated by the workflow.",
                    "source": {
                        "output_files": list(output_files),
                        "strace_file": self.strace_file,
                        "target_scripts_dir": self.target_scripts_dir
                    }
                })

        return {
            "updated_workflow": yaml.dump(updated_workflow, default_flow_style=False),
            "recommendations": self.recommendations
        }
